default:
  tags:
    - deployment

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE/frontend:latest


stages:
  - quality
  - build
  - test
  - docker
  - deploy

frontend:code_quality:
  stage: quality
  before_script:
    - cd client
  script:
    - pnpm install
    - pnpm prettier --check .
  allow_failure: true

frontend:build:
  stage: build
  before_script:
    - cd client
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 hour

frontend:unit_test:
  stage: test
  before_script:
    - cd client
  script:
    - pnpm install
    - pnpm test
  dependencies:
    - frontend:build
  allow_failure: true

frontend:docker_build:
  stage: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg VITE_API_BASE=$VITE_API_BASE -t $IMAGE_TAG -t $IMAGE_LATEST -f client/Dockerfile client/
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST
  dependencies:
    - frontend:build
  environment:
    name: $DEPLOY_ENV

frontend:deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p $HOST_PORT:80 --network kochservice-network --restart unless-stopped $IMAGE_TAG
  environment:
    name: $DEPLOY_ENV
    url: $DEPLOY_URL
