/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeNewRouteImport } from './routes/recipe/new'
import { Route as RecipeIdRouteImport } from './routes/recipe/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeNewRoute = RecipeNewRouteImport.update({
  id: '/recipe/new',
  path: '/recipe/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/recipe/$id'
    | '/recipe/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/recipe/$id'
    | '/recipe/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/recipe/$id'
    | '/recipe/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookmarksRoute: typeof BookmarksRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  RecipeIdRoute: typeof RecipeIdRoute
  RecipeNewRoute: typeof RecipeNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/new': {
      id: '/recipe/new'
      path: '/recipe/new'
      fullPath: '/recipe/new'
      preLoaderRoute: typeof RecipeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookmarksRoute: BookmarksRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  RecipeIdRoute: RecipeIdRoute,
  RecipeNewRoute: RecipeNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
