/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import { axiosClient } from '../../lib/axios-client'

export const getSentry = () => {
  const sentryTunnel = (sentryTunnelBody: string) => {
    return axiosClient<void>({
      url: `/sentry-tunnel`,
      method: 'POST',
      headers: { 'Content-Type': 'application/x-sentry-envelope' },
      data: sentryTunnelBody,
    })
  }
  return { sentryTunnel }
}
export type SentryTunnelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSentry>['sentryTunnel']>>
>
