default:
  tags:
    - deployment

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE/backend:latest

cache:
  key:
    files:
      - server/Cargo.lock
  paths:
    - server/target/

stages:
  - quality
  - build
  - test
  - docker
  - deploy

backend:code_quality:
  stage: quality
  before_script:
    - rustup component add rustfmt clippy
    - cd server
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
  allow_failure: true

backend:build:
  stage: build
  before_script:
    - cd server
  script:
    - cargo build --release
  artifacts:
    paths:
      - server/target/release/kochservice
      - server/Cargo.lock
    expire_in: 1 hour

backend:test:
  stage: test
  before_script:
    - cd server
  script:
    - cargo test --release

backend:docker_build:
  stage: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_LATEST -f server/Dockerfile server/
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST
  dependencies:
    - backend:build

backend:deploy_dev:
  stage: deploy
  environment: development
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker stop backend_dev || true
    - docker rm backend_dev || true
    - docker run -d --name backend_dev -p 8180:8080 -e DATABASE_URL=$DATABASE_URL_DEV --network kochservice-network --restart unless-stopped $IMAGE_TAG

backend:deploy:
  stage: deploy
  environment: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker stop backend || true
    - docker rm backend || true
    - docker run -d --name backend -p 8080:8080 -e DATABASE_URL=$DATABASE_URL_PROD --network kochservice-network --restart unless-stopped $IMAGE_TAG
