variables:
  BACKEND_IMAGE_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
  BACKEND_IMAGE_LATEST: $CI_REGISTRY_IMAGE/backend:latest

cache:
  key:
    files:
      - server/Cargo.lock
  paths:
    - server/target/x86_64-unknown-linux-musl/

backend:code_quality:
  stage: quality
  before_script:
    - cd server
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
  allow_failure: true

backend:build:
  stage: build
  before_script:
    - cd server
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - server/target/x86_64-unknown-linux-musl/release/kochservice
      - server/Cargo.lock
    expire_in: 1 hour

backend:test:
  stage: test
  before_script:
    - cd server
  script:
    - cargo test --release

backend:docker_build:
  stage: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $BACKEND_IMAGE_TAG -t $BACKEND_IMAGE_LATEST -f server/Dockerfile server/
    - docker push $BACKEND_IMAGE_TAG
    - docker push $BACKEND_IMAGE_LATEST
  dependencies:
    - backend:build

backend:deploy:
  stage: deploy
  environment:
    name: $DEPLOY_ENV/server
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $BACKEND_IMAGE_TAG
    - docker stop $BACKEND_CONTAINER || true
    - docker rm $BACKEND_CONTAINER || true
    - docker run -d --name $BACKEND_CONTAINER -p $BACKEND_PORT:8080 -e DATABASE_URL=$DATABASE_URL -e SENTRY_DSN=$SENTRY_DSN -e SENTRY_DSN_CLIENT=$SENTRY_DSN_CLIENT -e RUST_LOG=$RUST_LOG -e DEPLOY_ENV=$DEPLOY_ENV --network kochservice-network --restart unless-stopped $BACKEND_IMAGE_TAG
