/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateIngredientRequest,
  IngredientResponse,
  IngredientsResponse,
  UpdateIngredientRequest,
} from '../kochservice.schemas'

import { axiosClient } from '../../lib/axios-client'

export const getIngredients = () => {
  const getIngredients = () => {
    return axiosClient<IngredientsResponse>({
      url: `/ingredient`,
      method: 'GET',
    })
  }
  const createIngredient = (
    createIngredientRequest: CreateIngredientRequest,
  ) => {
    return axiosClient<IngredientResponse>({
      url: `/ingredient`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createIngredientRequest,
    })
  }
  const getIngredient = (id: string) => {
    return axiosClient<IngredientResponse>({
      url: `/ingredient/${id}`,
      method: 'GET',
    })
  }
  const updateIngredient = (
    id: string,
    updateIngredientRequest: UpdateIngredientRequest,
  ) => {
    return axiosClient<IngredientResponse>({
      url: `/ingredient/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateIngredientRequest,
    })
  }
  const deleteIngredient = (id: string) => {
    return axiosClient<IngredientResponse>({
      url: `/ingredient/${id}`,
      method: 'DELETE',
    })
  }
  return {
    getIngredients,
    createIngredient,
    getIngredient,
    updateIngredient,
    deleteIngredient,
  }
}
export type GetIngredientsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIngredients>['getIngredients']>>
>
export type CreateIngredientResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIngredients>['createIngredient']>>
>
export type GetIngredientResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIngredients>['getIngredient']>>
>
export type UpdateIngredientResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIngredients>['updateIngredient']>>
>
export type DeleteIngredientResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIngredients>['deleteIngredient']>>
>
