/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateTagRequest,
  TagResponse,
  TagsResponse,
  UpdateTagRequest,
} from '../kochservice.schemas'

import { axiosClient } from '../../lib/axios-client'

export const getTags = () => {
  const getTags = () => {
    return axiosClient<TagsResponse>({ url: `/tag`, method: 'GET' })
  }
  const createTag = (createTagRequest: CreateTagRequest) => {
    return axiosClient<TagResponse>({
      url: `/tag`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTagRequest,
    })
  }
  const getTag = (id: string) => {
    return axiosClient<TagResponse>({ url: `/tag/${id}`, method: 'GET' })
  }
  const updateTag = (id: string, updateTagRequest: UpdateTagRequest) => {
    return axiosClient<TagResponse>({
      url: `/tag/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateTagRequest,
    })
  }
  const deleteTag = (id: string) => {
    return axiosClient<TagResponse>({ url: `/tag/${id}`, method: 'DELETE' })
  }
  return { getTags, createTag, getTag, updateTag, deleteTag }
}
export type GetTagsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>['getTags']>>
>
export type CreateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>['createTag']>>
>
export type GetTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>['getTag']>>
>
export type UpdateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>['updateTag']>>
>
export type DeleteTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>['deleteTag']>>
>
