/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import { apiClient } from '../../lib/api-client'

export type healthResponse200 = {
  data: void
  status: 200
}

export type healthResponseSuccess = healthResponse200 & {
  headers: Headers
}
export type healthResponse = healthResponseSuccess

export const getHealthUrl = () => {
  return `/health`
}

export const health = async (
  options?: RequestInit,
): Promise<healthResponse> => {
  return apiClient<healthResponse>(getHealthUrl(), {
    ...options,
    method: 'GET',
  })
}
