/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import { axiosClient } from '../../lib/axios-client'

export const getHealth = () => {
  const health = () => {
    return axiosClient<void>({ url: `/health`, method: 'GET' })
  }
  return { health }
}
export type HealthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHealth>['health']>>
>
