/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateIngredientRequest,
  IngredientResponse,
  IngredientsResponse,
  UpdateIngredientRequest,
} from '../kochservice.schemas'

import { apiClient } from '../../lib/api-client'

export type getIngredientsResponse200 = {
  data: IngredientsResponse
  status: 200
}

export type getIngredientsResponseSuccess = getIngredientsResponse200 & {
  headers: Headers
}
export type getIngredientsResponse = getIngredientsResponseSuccess

export const getGetIngredientsUrl = () => {
  return `/ingredient`
}

export const getIngredients = async (
  options?: RequestInit,
): Promise<getIngredientsResponse> => {
  return apiClient<getIngredientsResponse>(getGetIngredientsUrl(), {
    ...options,
    method: 'GET',
  })
}

export type createIngredientResponse201 = {
  data: IngredientResponse
  status: 201
}

export type createIngredientResponseSuccess = createIngredientResponse201 & {
  headers: Headers
}
export type createIngredientResponse = createIngredientResponseSuccess

export const getCreateIngredientUrl = () => {
  return `/ingredient`
}

export const createIngredient = async (
  createIngredientRequest: CreateIngredientRequest,
  options?: RequestInit,
): Promise<createIngredientResponse> => {
  return apiClient<createIngredientResponse>(getCreateIngredientUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createIngredientRequest),
  })
}

export type getIngredientResponse200 = {
  data: IngredientResponse
  status: 200
}

export type getIngredientResponseSuccess = getIngredientResponse200 & {
  headers: Headers
}
export type getIngredientResponse = getIngredientResponseSuccess

export const getGetIngredientUrl = (id: string) => {
  return `/ingredient/${id}`
}

export const getIngredient = async (
  id: string,
  options?: RequestInit,
): Promise<getIngredientResponse> => {
  return apiClient<getIngredientResponse>(getGetIngredientUrl(id), {
    ...options,
    method: 'GET',
  })
}

export type updateIngredientResponse200 = {
  data: IngredientResponse
  status: 200
}

export type updateIngredientResponseSuccess = updateIngredientResponse200 & {
  headers: Headers
}
export type updateIngredientResponse = updateIngredientResponseSuccess

export const getUpdateIngredientUrl = (id: string) => {
  return `/ingredient/${id}`
}

export const updateIngredient = async (
  id: string,
  updateIngredientRequest: UpdateIngredientRequest,
  options?: RequestInit,
): Promise<updateIngredientResponse> => {
  return apiClient<updateIngredientResponse>(getUpdateIngredientUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateIngredientRequest),
  })
}

export type deleteIngredientResponse200 = {
  data: IngredientResponse
  status: 200
}

export type deleteIngredientResponseSuccess = deleteIngredientResponse200 & {
  headers: Headers
}
export type deleteIngredientResponse = deleteIngredientResponseSuccess

export const getDeleteIngredientUrl = (id: string) => {
  return `/ingredient/${id}`
}

export const deleteIngredient = async (
  id: string,
  options?: RequestInit,
): Promise<deleteIngredientResponse> => {
  return apiClient<deleteIngredientResponse>(getDeleteIngredientUrl(id), {
    ...options,
    method: 'DELETE',
  })
}
