//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::ingredient::Entity as Ingredient;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
pub use super::recipe_tag::Entity as RecipeTag;
pub use super::tag::Entity as Tag;
