/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateRecipeRequest,
  GetRecipesParams,
  RecipeResponse,
  RecipesResponse,
  UpdateRecipeRequest,
} from '../kochservice.schemas'

import { axiosClient } from '../../lib/axios-client'

export const getRecipes = () => {
  const getRecipes = (params: GetRecipesParams) => {
    return axiosClient<RecipesResponse>({
      url: `/recipe`,
      method: 'GET',
      params,
    })
  }
  const createRecipe = (createRecipeRequest: CreateRecipeRequest) => {
    return axiosClient<RecipeResponse>({
      url: `/recipe`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRecipeRequest,
    })
  }
  const getRecipe = (id: string) => {
    return axiosClient<RecipeResponse>({ url: `/recipe/${id}`, method: 'GET' })
  }
  const updateRecipe = (
    id: string,
    updateRecipeRequest: UpdateRecipeRequest,
  ) => {
    return axiosClient<RecipeResponse>({
      url: `/recipe/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateRecipeRequest,
    })
  }
  const deleteRecipe = (id: string) => {
    return axiosClient<RecipeResponse>({
      url: `/recipe/${id}`,
      method: 'DELETE',
    })
  }
  return { getRecipes, createRecipe, getRecipe, updateRecipe, deleteRecipe }
}
export type GetRecipesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipes>['getRecipes']>>
>
export type CreateRecipeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipes>['createRecipe']>>
>
export type GetRecipeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipes>['getRecipe']>>
>
export type UpdateRecipeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipes>['updateRecipe']>>
>
export type DeleteRecipeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipes>['deleteRecipe']>>
>
