/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * kochservice
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateRecipeRequest,
  GetRecipesParams,
  RecipeResponse,
  RecipesResponse,
  UpdateRecipeRequest,
} from '../kochservice.schemas'

import { apiClient } from '../../lib/api-client'

export type getRecipesResponse200 = {
  data: RecipesResponse
  status: 200
}

export type getRecipesResponseSuccess = getRecipesResponse200 & {
  headers: Headers
}
export type getRecipesResponse = getRecipesResponseSuccess

export const getGetRecipesUrl = (params: GetRecipesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/recipe?${stringifiedParams}`
    : `/recipe`
}

export const getRecipes = async (
  params: GetRecipesParams,
  options?: RequestInit,
): Promise<getRecipesResponse> => {
  return apiClient<getRecipesResponse>(getGetRecipesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export type createRecipeResponse201 = {
  data: RecipeResponse
  status: 201
}

export type createRecipeResponseSuccess = createRecipeResponse201 & {
  headers: Headers
}
export type createRecipeResponse = createRecipeResponseSuccess

export const getCreateRecipeUrl = () => {
  return `/recipe`
}

export const createRecipe = async (
  createRecipeRequest: CreateRecipeRequest,
  options?: RequestInit,
): Promise<createRecipeResponse> => {
  return apiClient<createRecipeResponse>(getCreateRecipeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRecipeRequest),
  })
}

export type getRecipeResponse200 = {
  data: RecipeResponse
  status: 200
}

export type getRecipeResponseSuccess = getRecipeResponse200 & {
  headers: Headers
}
export type getRecipeResponse = getRecipeResponseSuccess

export const getGetRecipeUrl = (id: string) => {
  return `/recipe/${id}`
}

export const getRecipe = async (
  id: string,
  options?: RequestInit,
): Promise<getRecipeResponse> => {
  return apiClient<getRecipeResponse>(getGetRecipeUrl(id), {
    ...options,
    method: 'GET',
  })
}

export type updateRecipeResponse200 = {
  data: RecipeResponse
  status: 200
}

export type updateRecipeResponseSuccess = updateRecipeResponse200 & {
  headers: Headers
}
export type updateRecipeResponse = updateRecipeResponseSuccess

export const getUpdateRecipeUrl = (id: string) => {
  return `/recipe/${id}`
}

export const updateRecipe = async (
  id: string,
  updateRecipeRequest: UpdateRecipeRequest,
  options?: RequestInit,
): Promise<updateRecipeResponse> => {
  return apiClient<updateRecipeResponse>(getUpdateRecipeUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRecipeRequest),
  })
}

export type deleteRecipeResponse200 = {
  data: RecipeResponse
  status: 200
}

export type deleteRecipeResponseSuccess = deleteRecipeResponse200 & {
  headers: Headers
}
export type deleteRecipeResponse = deleteRecipeResponseSuccess

export const getDeleteRecipeUrl = (id: string) => {
  return `/recipe/${id}`
}

export const deleteRecipe = async (
  id: string,
  options?: RequestInit,
): Promise<deleteRecipeResponse> => {
  return apiClient<deleteRecipeResponse>(getDeleteRecipeUrl(id), {
    ...options,
    method: 'DELETE',
  })
}
